import { Injectable } from '@nestjs/common';
import { Transaction } from '../../domain/entities/Transaction';
import { TransactionRepository } from '../../domain/repositories/TransactionRepository';

export class CreateTransactionDto {
  orderNumber: string;
  amount: number;
  paymentMethod: string;
  status: string;
  staffName: string;
}

@Injectable()
export class CreateTransactionUseCase {
  constructor(private readonly transactionRepository: TransactionRepository) {}

  async execute(data: CreateTransactionDto): Promise<void> {
    const transaction = new Transaction(
      0, // ID will be generated by DB
      data.orderNumber,
      data.amount,
      data.paymentMethod,
      data.status,
      data.staffName,
      new Date(),
    );

    await this.transactionRepository.save(transaction);
  }
}
